server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tyqttt?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource